export const flagsHash = {
  0: {
    val: 0,
    description: "zero",
    label: "Q",
    selectable: true,
    color: "orange",
    color10: "green",
    labelcolor: "label-zero",
  },
  1: {
    val: 1,
    description: "valid",
    label: "K",
    selectable: true,
    color: "#BF0B23",
    color10: "transparent",
    labelcolor: "label-danger",
  },
  2: {
    val: 2,
    description: "span",
    label: "Q",
    selectable: true,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  3: {
    val: 3,
    description: "span",
    label: "Q",
    selectable: false,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  4: {
    val: 4,
    description: "span",
    label: "Q",
    selectable: false,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  5: {
    val: 5,
    description: "span",
    label: "Q",
    selectable: false,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  6: {
    val: 6,
    description: "span",
    label: "Q",
    selectable: false,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  7: {
    val: 7,
    description: "span",
    label: "Q",
    selectable: false,
    color: "orange",
    color10: "green",
    labelcolor: "label-warning",
  },
  8: {
    val: 8,
    description: "maintenance",
    label: "P",
    selectable: true,
    color: "grey",
    color10: "darkgrey",
    labelcolor: "label-info",
  },
  9: {
    val: 9,
    description: "offline",
    label: "N",
    selectable: true,
    color: "black",
    color10: "black",
    labelcolor: "label-default",
  },
  10: {
    val: 10,
    description: "2TAPs",
    label: "K",
    selectable: true,
    color: "#BF0B23",
    color10: "black",
    labelcolor: "label-danger",
  },
};

export const colorsHash = {
  1: {
    val: 1,
    description: "RedCoeff",
    label: "R",
    selectable: true,
    color: "#BF0B23",
    color10: "black",
    labelcolor: "label-danger",
  },
  2: {
    val: 2,
    description: "BlueCoeff",
    label: "B",
    selectable: true,
    color: "#3333ff",
    color10: "black",
    labelcolor: "label-danger",
  },
  3: {
    val: 3,
    description: "GreenCoeff",
    label: "G",
    selectable: true,
    color: "#00cc00",
    color10: "black",
    labelcolor: "label-danger",
  },
  4: {
    val: 4,
    description: "Black",
    label: "BL",
    selectable: true,
    color: "black",
    color10: "black",
    labelcolor: "label-danger",
  },
  5: {
    val: 5,
    description: "Dark Red",
    label: "DR",
    selectable: true,
    color: "#3f007a",
    labelcolor: "label-danger",
  },
  6: {
    val: 6,
    description: "Glossy Red",
    label: "GR",
    selectable: true,
    color: "#007a55",
    labelcolor: "label-danger",
  },
};

export const channelHash = {
  RMY_WS: 1,
  RMY_WD: 2,
  TRH_Temp: 6,
  HMP60_Temp: 6,
  TRH_RH: 38,
  HMP60_RH: 38,
  O3_O3conc: 25,
  TEOM_MassConc: 43,
  TEOM_AmbTemp: 70,
  NOx_NOconc: 28,
  NOy_NOyconc: 34,
  NOx_NO2conc: 29,
  NOx_NOxconc: 30,
  NOy_NOyConc: 34,
  NO_NOConc: 28,
  NO2_NO2Conc: 29,
  NOx_NO2Conc: 29,
  Rain_Precip: 8,
  Baro_Press: 9,
  CO_COconc: 27,
  SO_SO2conc: 26,
  SO2_SO2conc: 26,
  SO2_SO2Conc: 26,
};

export const unitsHash = {
  O3: "pbbv",
  Conc: "pbbv",
  conc: "pbbv",
  NO: "pbbv",
  NO2: "pbbv",
  NOx: "pbbv",
  WS: "meter/second",
  WD: "degree",
  Temp: "degree C",
  TEMP: "degree C",
  RH: "percent",
  MassConc: "ugm3",
  AmbTemp: "C",
};
